/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProgrammesRouteImport } from './routes/programmes'
import { Route as PiliersRouteImport } from './routes/piliers'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as EvenementsRouteImport } from './routes/evenements'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesRoute = ProgrammesRouteImport.update({
  id: '/programmes',
  path: '/programmes',
  getParentRoute: () => rootRouteImport,
} as any)
const PiliersRoute = PiliersRouteImport.update({
  id: '/piliers',
  path: '/piliers',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const EvenementsRoute = EvenementsRouteImport.update({
  id: '/evenements',
  path: '/evenements',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/evenements': typeof EvenementsRoute
  '/impact': typeof ImpactRoute
  '/piliers': typeof PiliersRoute
  '/programmes': typeof ProgrammesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/evenements': typeof EvenementsRoute
  '/impact': typeof ImpactRoute
  '/piliers': typeof PiliersRoute
  '/programmes': typeof ProgrammesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/evenements': typeof EvenementsRoute
  '/impact': typeof ImpactRoute
  '/piliers': typeof PiliersRoute
  '/programmes': typeof ProgrammesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/contact'
    | '/evenements'
    | '/impact'
    | '/piliers'
    | '/programmes'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/contact'
    | '/evenements'
    | '/impact'
    | '/piliers'
    | '/programmes'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/contact'
    | '/evenements'
    | '/impact'
    | '/piliers'
    | '/programmes'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  ContactRoute: typeof ContactRoute
  EvenementsRoute: typeof EvenementsRoute
  ImpactRoute: typeof ImpactRoute
  PiliersRoute: typeof PiliersRoute
  ProgrammesRoute: typeof ProgrammesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes': {
      id: '/programmes'
      path: '/programmes'
      fullPath: '/programmes'
      preLoaderRoute: typeof ProgrammesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/piliers': {
      id: '/piliers'
      path: '/piliers'
      fullPath: '/piliers'
      preLoaderRoute: typeof PiliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evenements': {
      id: '/evenements'
      path: '/evenements'
      fullPath: '/evenements'
      preLoaderRoute: typeof EvenementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  ContactRoute: ContactRoute,
  EvenementsRoute: EvenementsRoute,
  ImpactRoute: ImpactRoute,
  PiliersRoute: PiliersRoute,
  ProgrammesRoute: ProgrammesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
